#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: solang-vscode
  description: A VSCode plugin for a Solidity to WASM compiler written in Rust
  homepage: https://wiki.hyperledger.org/display/labs
  default_branch: master
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
