
on: [push, pull_request]

name: Rust

jobs:
  build:
    name: Build and format
    runs-on: ubuntu-latest
    container: hyperledgerlabs/solang:ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust stable
        run: rustup default stable
        working-directory: solang-server
      - name: Compile stdlib
        run: clang-10 --target=wasm32 -c -emit-llvm -O3 -ffreestanding -fno-builtin -Wall stdlib.c sha3.c substrate.c ripemd160.c
        working-directory:  ./stdlib
      - run: cargo build
        working-directory: solang-server
      - run: cargo clippy
        working-directory: solang-server
      - run: cargo fmt --all
        working-directory: solang-server
