
on: [push, pull_request]

name: Rust

jobs:
  build:
    name: Build and format
    runs-on: ubuntu-latest
    container: hyperledgerlabs/solang:ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install llvm
      - run: sudo apt install curl llvm-10-dev clang-10
      - name: Build cargo
      - run: cargo build
        working-directory: solang-server
      - run: cargo clippy
        working-directory: solang-server
      - run: cargo fmt --all
        working-directory: solang-server
